name: ml-r
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - jupyterlab
  - r-base=4.2.3
  - r-caret
  - r-ggplot2
  - r-irkernel
  - r-kernlab
  - r-class
  - r-mass
  - r-randomforest
  - r-rpart
